### ISSUE TITLE
Problem with web scraping

### ISSUE THREAD

**Issue by hihohah** [BuissonFlorent/GoodReads_TextMining#2]
Hello, thanks for writing the script. 

I'm having problem running startServer(), it returns an error:

Error: startServer is now defunct. Users in future can find the function in 
file.path(find.package("RSelenium"), "examples/serverUtils"). The
recommended way to run a selenium server is via Docker. Alternatively
see the RSelenium::rsDriver function.

I'm not good with coding so I can't figure out how to do this... It would be extremely helpful if there is a solution.

Thank you!

**Comment by BuissonFlorent** [comment]
Hello,
Thanks for your message! There has been a big update of Selenium, which essentially breaks down the back office of the previous solution. The solution now is to install and run a selenium server in a virtual environment via Docker. You'll find the instructions there: 
https://cran.r-project.org/web/packages/RSelenium/vignettes/RSelenium-docker.html
I feel that walkthrough is pretty clear, it should allow you to get it done (I managed to replicate my previous analyses this way). I don't know anything about docker beyond that page, so that's all I can tell you. Sorry about that!
